### ISSUE TITLE
Does it work with Rails 5.1.4 and Spree 3.3.2?

### ISSUE THREAD

**Issue by tathspts** [vinsol-spree-contrib/spree_themes#7]
Hi I was wondering if it works with Rails 5.1.4 and Spree 3.3.2?

**Comment by tanmay3011** [comment]
@tathspts Yes! This should work with Spree 3.3

**Comment by tathspts** [comment]
getting this error

/public/vinsol_spree_themes/current/views/spree/shared/_header.html.erb where line #13 raised:

undefined method `store_menu?' for #<#<Class:0x007faaa7078c68>:0x007faaa708afa8>

**Comment by tanmay3011** [comment]
@tathspts Thanks for reporting this bug. This method has been recently removed from [Spree](https://github.com/spree/spree/commit/39e4961a19b2724bbe2986a8100f1e931fad08fe#diff-c4fbb726239a24146c0c16a33538c4bc)

Will provide a fix ASAP.

**Comment by nakamuraagatha** [comment]
Getting error on search 

```
undefined local variable or method `cache_key_for_taxons' for #<#<Class:0x00000006d18c50>:0x00000006d0cdd8>

```
Did you mean?  cache_key_for_products

**Comment by tanmay3011** [comment]
Hey @nakamuraagatha 
I have already updated few themes and there are PR's that are pending for review but you can use these branches for Spree >= 3.3.0

1.  [Default](https://github.com/vinsol-spree-contrib/spree_themes/tree/3-3-bump/lib/generators/themes) 
2.  [theme-ClassicWhite](https://github.com/vinsol-spree-contrib/theme-ClassicWhite/pull/1)
3.  [theme-BigShop](https://github.com/vinsol-spree-contrib/theme-BigShop/pull/1)

**Comment by PareshGupta** [comment]
@nakamuraagatha The extension is upgraded to work with `spree 3.2`. I am closing this issue.

**Comment by jungbunzlav** [comment]
I am using **spree 3.4.4** and **vinsol_spree_themes 0.0.1 (at master@5c5b7a0)** and I am getting still the error

```
undefined local variable or method `cache_key_for_taxons' for #<#<Class:0x00007f7ef06747f8>:0x00007f7ef0643d60>
Did you mean?  cache_key_for_products
```

Is there any way around this issue?

**Comment by jungbunzlav** [comment]
Due to the differen spree version I opened a new issue: https://github.com/vinsol-spree-contrib/spree_themes/issues/17
